name: "Integrity"

on:
  pull_request: null
  push:
    branches:
      - "master"

jobs:
  call_workflow_integrity:
    name: "Integrity"
    uses: "szepeviktor/byte-level-care/.github/workflows/integrity.yml@master"
